# -*- coding: utf-8 -*-
"""판다스와 통계기초.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w65SDK9g_-WOgZsySoOKd8VDvd36DTtv

평균
"""

list(range(10))

import random

sales = [random.randint(1,10) for i in range(10)]
sales

mean = sum(sales)/len(sales)
mean

import pandas as pd
df = pd.DataFrame(sales,columns=['sales'])
df

df.mean()

"""표준 편차"""

import random
sales = [random.randint(1,10) for i in range(10)]
sales

mean = sum(sales)/len(sales)
mean

deviations = [round(s-mean,2) for s in sales]
deviations

import math
분산 = sum([d**2 for d in deviations])/len(deviations)
표준편차 = math.sqrt(분산)
print(분산, 표준편차)

# 0 - 남성, 1 - 여성
genders = [0, 0, 0, 1, 1, 1, 1, 1, 1, 1]
sum(genders)/len(genders)

import pandas as pd
df = pd.DataFrame(sales,columns = ['sales'])
df

df['sales'].std()

"""중앙값"""

import random

sales = [random.randint(1,10) for i in range(10)]
sales.sort()
print(sales)

# // - 몫을 구하는 연산자
n = len(sales)//2

if len(sales)%2 == 0:
  print(sum(sales[n-1:n+1])/2)
else:
  print(sales[n])

import pandas as pd
df = pd.DataFrame(sales,columns = ['sales'])
df['sales'].median()

"""사분위수"""

import random

sales = [random.randint(1,100) for i in range(16)]
sales.sort()
print(sales)

# n = (len(sales)//4)
# print('count',n)
# print(f'{sales[n]}, {sales[2*n]}, {sales[3*n]}') 잘못된 코드

import pandas as pd

df = pd.DataFrame(sales, columns = ['sales'])
df

df['sales'].quantile([0,.25,.5,.75,1])

df.describe()

players = {
    'p1': [7,9,9,10,10,10,10,10,11,11,13],
    'p2': [7,8,9,9,10,10,10,11,11,12,13],
    'p3': [3,3,6,7,7,10,10,10,11,13,30]
}

import pandas as pd

df = pd.DataFrame(players)
df

df.describe()

"""list comprehension"""

numbers = list(range(10))
numbers

evens = [n for n in numbers if n%2 == 0]
print(evens)

evens = []
for n in numbers:
  if n%2 == 0:
    evens.append(n)
print(evens)

odds = [n for n in numbers if n%2 != 0]
print(odds)

squre_evens = [n**2 for n in numbers if n%2 == 0]
print(squre_evens)

"""slicing - 부분집합 꺼내기"""

numbers[-3:]